#!/bin/bash

START_COMMAND="java -jar reverse-mobius.jar -conf conf.json"

source $OPENSHIFT_CARTRIDGE_SDK_BASH

if [ -z "$(ps -ef | grep $START_COMMAND | grep -v grep)" ]
then
    client_result "Application is already stopped"
else
    kill `ps -ef | grep $START_COMMAND | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
